settings:
  batch_size: 15
  test_title: original
  input_hw: [384, 640]
  half: True
  auto: False
  pre_multi: True
  infer_multi: False
  post_multi: False

models:
  model1:
    model_type: yolov5
    engine_file: /home/laughing/yolov5/runs/experiment/original/weights/best-15.engine
    conf_thres: 0.4
    iou_thres: 0.4
    filter: null
    names: ./weights/trt/person_head.yaml

  model2:
    model_type: yolov5
    engine_file: /home/laughing/yolov5/runs/experiment/original/weights/best-15.engine
    conf_thres: 0.4
    iou_thres: 0.4
    filter: null
    names: ./weights/trt/person_head.yaml

  model3:
    model_type: yolov5
    engine_file: /home/laughing/yolov5/runs/experiment/original/weights/best-15.engine
    conf_thres: 0.4
    iou_thres: 0.4
    filter: null
    names: ./weights/trt/person_head.yaml

  model4:
    model_type: yolov5
    engine_file: /home/laughing/yolov5/runs/experiment/original/weights/best-15.engine
    conf_thres: 0.4
    iou_thres: 0.4
    filter: null
    names: ./weights/trt/person_head.yaml

  model5:
    model_type: yolov5
    engine_file: /home/laughing/yolov5/runs/experiment/original/weights/best-15.engine
    conf_thres: 0.4
    iou_thres: 0.4
    filter: null
    names: ./weights/trt/person_head.yaml
