# model1:
#   model_type: yolov5
#   yaml: ./weights/yolov5/yolov5s.yaml
#   weight: ./weights/yolov5/yolov5s.pth
#   conf_thres: 0.4
#   iou_thres: 0.4
#   filter: null
# 
# model2:
#   model_type: yolov5
#   yaml: ./weights/yolov5/play_phone.yaml
#   weight: ./weights/yolov5/play_phone.pth
#   conf_thres: 0.4
#   iou_thres: 0.4
#   filter: null
# 
# model3:
#   model_type: yolov5
#   yaml: ./weights/yolov5/phone.yaml
#   weight: ./weights/yolov5/phone.pth
#   conf_thres: 0.4
#   iou_thres: 0.4
#   filter: null
# 
# model4:
#   model_type: yolox
#   yaml: ./weights/yolox/yolox_nano.yaml
#   weight: ./weights/yolox/yolox_nano.pth
#   conf_thres: 0.4
#   iou_thres: 0.4
#   filter: null

# ----global config--------

model1:
  model_type: yolov5
  weight: ./weights/yolov5/yolov5n.pt
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null

model2:
  model_type: yolov5
  weight: ./weights/yolov5/yolov5n.pt
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null

model3:
  model_type: yolov5
  weight: ./weights/yolov5/yolov5n.pt
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null

model4:
  model_type: yolov5
  weight: ./weights/yolov5/yolov5n.pt
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null

model5:
  model_type: yolov5
  weight: ./weights/yolov5/yolov5n.pt
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
