model1:
  engine_file: /home/laughing/yolov5/weights/engine/yolov5n15.engine
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
  names: ./weights/trt/yolov5n.yaml

model2:
  engine_file: /home/laughing/yolov5/weights/engine/yolov5n15.engine
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
  names: ./weights/trt/yolov5n.yaml

model3:
  engine_file: /home/laughing/yolov5/weights/engine/yolov5n15.engine
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
  names: ./weights/trt/yolov5n.yaml

model4:
  engine_file: /home/laughing/yolov5/weights/engine/yolov5n15.engine
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
  names: ./weights/trt/yolov5n.yaml

model5:
  engine_file: /home/laughing/yolov5/weights/engine/yolov5n15.engine
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
  names: ./weights/trt/yolov5n.yaml
