model1:
  model_type: yolov5
  engine_file: /home/laughing/yolov5/weights/engine/yolov5n416-15.engine
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
  names: ./weights/trt/yolov5n.yaml

model2:
  model_type: yolov5
  engine_file: /home/laughing/yolov5/weights/engine/yolov5n416-15.engine
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
  names: ./weights/trt/yolov5n.yaml

model3:
  model_type: yolov5
  engine_file: /home/laughing/yolov5/weights/engine/yolov5n416-15.engine
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
  names: ./weights/trt/yolov5n.yaml

model4:
  model_type: yolov5
  engine_file: /home/laughing/yolov5/weights/engine/yolov5n416-15.engine
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
  names: ./weights/trt/yolov5n.yaml

model5:
  model_type: yolov5
  engine_file: /home/laughing/yolov5/weights/engine/yolov5n416-15.engine
  conf_thres: 0.4
  iou_thres: 0.4
  filter: null
  names: ./weights/trt/yolov5n.yaml
